Presentation.Web.AspDotNetCore.Client/Pages/ApplyLeave.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sylvia.Common;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{


    public class ApplyLeaveModel : PageModel
    {
        DBCommandProvider dBCommandProvider = new DBCommandProvider();
        public string Address { get; set; }
        public UserDS userDS { get; set; }
        public CountryDS countryDS { get; set; }
        public CountryDS divisionLs { get; set; }
        public int CountryId { get; set; }
        public int DivisionId { get; set; }
        public string CountrySelectedText { get; set; }


        public void OnGetGetRdlcReport()
        {
            
        }

        public void OnGet()
        {
            int _conId = ADOController.Instance.OpenNewConnection();
            ErrorDS errDS = new ErrorDS();
            userDS = new UserDS();
            DataStringDS stringDS = new DataStringDS();
            bool bError = false;
            int nRowAffected = -1;

            OleDbCommand cmd = dBCommandProvider.GetDBCommandAdvanced("GetUser_For_Login", "User.xml");
            if (cmd == null)
            {
                Util.LogInfo("Command is null.");
                return;
            }
            cmd.Parameters["LoginID"].Value = "admin";

            OleDbDataAdapter adapter = new OleDbDataAdapter();
            adapter.SelectCommand = cmd;


            bError = false;
            nRowAffected = -1;
            nRowAffected = ADOController.Instance.Fill(adapter, userDS, userDS.Users.TableName, _conId, ref bError);
            if (bError)
            {
                ErrorDS.Error err = errDS.Errors.NewError();
                err.ErrorCode = ErrorCode.ERR_DB_OPERATION_FAILED.ToString();
                err.ErrorTier = ErrorTier.ERR_TIER_DL.ToString();
                err.ErrorLevel = ErrorLevel.ERR_LEVEL_SEVER.ToString();
                err.ErrorInfo1 = ActionID.NA_ACTION_GET_LOGIN_USER.ToString();
                errDS.Errors.AddError(err);
                errDS.AcceptChanges();

            }
            userDS.AcceptChanges();


            OleDbCommand cmd1 = dBCommandProvider.GetDBCommandAdvanced("GetAdministrativeRoleByLoginID", "User.xml");

            cmd1.Parameters["LoginID"].Value = "admin";

            OleDbDataAdapter adapter1 = new OleDbDataAdapter();
            adapter1.SelectCommand = cmd1;

            bError = false;
            nRowAffected = -1;
            nRowAffected = ADOController.Instance.Fill(adapter1, userDS, userDS.UAARole.TableName, _conId, ref bError);
            userDS.AcceptChanges();

            stringDS.Clear();
            stringDS.AcceptChanges();
            foreach (UserDS.User user in userDS.Users)
            {
                if (!user.IsSaltNull())
                {
                    stringDS.DataStrings.AddDataString(user.Salt);
                }
                stringDS.AcceptChanges();
            }
            ViewData.Add("loggedInName", userDS.Users[0].EmployeeName);
            this.LoadCountry();
        }

        private void LoadCountry()
        {
            CountryId = 16;
            CountrySelectedText = "BANGLADESH";
            this.LoadDivisionByCountryName(CountrySelectedText);
            countryDS = UtilUI.getCountryList(); // code to populate the grades list box
        }
        public void OnPostGetLoginUserName()
        {
            

           
        }

        private void LoadDivisionByCountryName(string countryName)
        {
            divisionLs = UtilUI.getDivisionList();
            if (divisionLs.Division != null)
            {
                DataRow[] foundRows = divisionLs.Division.Select("COUNTRYNAME='" + countryName + "'");
                divisionLs = new CountryDS();
                foreach (DataRow divRow in foundRows)
                { divisionLs.Division.ImportRow(divRow); }
                divisionLs.AcceptChanges();
            }
        }

        public JsonResult OnGetDivisionForAssignLeaveByCountryName(string countryName)
        {
            try
            {
                CountryDS divisionLs = UtilUI.getDivisionList();
                if (divisionLs.Division != null)
                {
                    DataRow[] foundRows = divisionLs.Division.Select("COUNTRYNAME='" + countryName + "'");
                    divisionLs = new CountryDS();
                    foreach (DataRow divRow in foundRows)
                    { divisionLs.Division.ImportRow(divRow); }
                    divisionLs.AcceptChanges();
                }


                StringWriter builder = new StringWriter();
                builder.WriteLine("[");
                if (divisionLs.Division != null)
                {
                    builder.WriteLine("{\"optionDisplay\":\"Choose..\",");
                    builder.WriteLine("\"optionValue\":\"0\"},");
                    for (int i = 0; i <= divisionLs.Division.Rows.Count - 1; i++)
                    {
                        builder.WriteLine("{\"optionDisplay\":\"" + divisionLs.Division.Rows[i]["Divisionname"] + "\",");
                        builder.WriteLine("\"optionValue\":\"" + divisionLs.Division.Rows[i]["Divisionid"] + "\"},");
                    }
                }
                else
                {
                    builder.WriteLine("{\"optionDisplay\":\"Select\",");
                    builder.WriteLine("\"optionValue\":\"0\"},");
                }


                string returnjson = builder.ToString().Substring(0, builder.ToString().Length - 3);
                returnjson = returnjson + "]";
                //return returnjson.Replace("\r", "").Replace("\n", "");
                return new JsonResult(returnjson.Replace("\r", "").Replace("\n", ""));

            }
            catch (Exception)
            {
                return new JsonResult(string.Empty);

            }

        }
    }

}

Presentation.Web.AspDotNetCore.Client/Pages/AssignLeave.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class AssignLeaveModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client
{
    public class ChangePasswordModel : PageModel
    {
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            return RedirectToPage("/dashboard");
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/Employees.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class EmployeesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/IframeForRDLCReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class IframeForRDLCReportModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/Index1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class Index1Model : PageModel
    {
        private readonly ILogger<Index1Model> _logger;

        public Index1Model(ILogger<Index1Model> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/LeaveReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sylvia.Common;
using Sylvia.Common.Reports;
using System.Data;
using System.IO;
using Sylvia.Common.RDLCReport;

namespace Presentation.Web.AspDotNetCore.Client
{
    public class LeaveReportModel : PageModel
    {
        DBCommandProvider dBCommandProvider = new DBCommandProvider();
        public EmployeeDS empDS { get; set; }
        public rptLeaveDS leaveDS { get; set; }
        public void OnGet()
        {
            int _conId = ADOController.Instance.OpenNewConnection();
            ErrorDS errDS = new ErrorDS();
            empDS = new EmployeeDS();
            DataStringDS stringDS = new DataStringDS();
            bool bError = false;
            int nRowAffected = -1;

            OleDbCommand cmd = dBCommandProvider.GetDBCommandAdvanced("GetEmployeeList_ForLeaveReport_SortByCode", "Employee.xml");
            if (cmd == null)
            {
                Util.LogInfo("Command is null.");
                return;
            }

            cmd.Parameters["EmployeeCode1"].Value = "6105";
            cmd.Parameters["EmployeeCode2"].Value = "6105";
            cmd.Parameters["EmployeeTypeID1"].Value = -1;
            cmd.Parameters["EmployeeTypeID2"].Value = -1;
            cmd.Parameters["CompanyCode1"].Value = "0";
            cmd.Parameters["CompanyCode2"].Value = "0";
            cmd.Parameters["LocationCode1"].Value = "0";
            cmd.Parameters["LocationCode2"].Value = "0";
            cmd.Parameters["SiteID1"].Value = 0;
            cmd.Parameters["SiteID2"].Value = 0;
            cmd.Parameters["CostCenterCode1"].Value = "0";
            cmd.Parameters["CostCenterCode2"].Value = "0";
            cmd.Parameters["CompanyDivisionCode1"].Value = "0";
            cmd.Parameters["CompanyDivisionCode2"].Value = "0";
            cmd.Parameters["DepartmentCode1"].Value = "0";
            cmd.Parameters["DepartmentCode2"].Value = "0";
            cmd.Parameters["FunctionCode1"].Value = "0";
            cmd.Parameters["FunctionCode2"].Value = "0";
            cmd.Parameters["LiabilityCode1"].Value = "0";
            cmd.Parameters["LiabilityCode2"].Value = "0";
            cmd.Parameters["GradeCode1"].Value = "0";
            cmd.Parameters["GradeCode2"].Value = "0";
            cmd.Parameters["DesignationCode1"].Value = "0";
            cmd.Parameters["DesignationCode2"].Value = "0";
            cmd.Parameters["EmployeeStatus1"].Value = -1;
            cmd.Parameters["EmployeeStatus2"].Value = -1;

            OleDbDataAdapter adapter = new OleDbDataAdapter();
            adapter.SelectCommand = cmd;


            bError = false;
            nRowAffected = -1;
            nRowAffected = ADOController.Instance.Fill(adapter, empDS, empDS.Employees.TableName, _conId, ref bError);
            if (bError)
            {
                ErrorDS.Error err = errDS.Errors.NewError();
                err.ErrorCode = ErrorCode.ERR_DB_OPERATION_FAILED.ToString();
                err.ErrorTier = ErrorTier.ERR_TIER_DL.ToString();
                err.ErrorLevel = ErrorLevel.ERR_LEVEL_SEVER.ToString();
                err.ErrorInfo1 = ActionID.NA_ACTION_GET_LOGIN_USER.ToString();
                errDS.Errors.AddError(err);
                errDS.AcceptChanges();

            }
            empDS.AcceptChanges();

        }
        public IActionResult OnPostRdlcReport()
        {
            int _conId = ADOController.Instance.OpenNewConnection();
            ErrorDS errDS = new ErrorDS();
            leaveDS = new rptLeaveDS();
            DataStringDS stringDS = new DataStringDS();
            bool bError = false;
            int nRowAffected = -1;
            OleDbCommand cmd = dBCommandProvider.GetDBCommandAdvanced("GetLeaveSummary", "rptLeave.xml");

          //  OleDbCommand cmd = DBCommandProvider.GetDBCommandAdvanced("GetLeaveSummary", "rptLeave.xml");
            if (cmd == null)
            {
                Util.LogInfo("Command is null.");
                return Page();
            }

            DateTime frmdate = new DateTime(2020, 01, 01);
            DateTime todate = new DateTime(2020, 12, 12);
            cmd.Parameters["FromDate"].Value = (object)frmdate;
            cmd.Parameters["ToDate"].Value = (object)todate;
            cmd.Parameters["ActivitiesID"].Value = "101";
            cmd.Parameters["ELQID"].Value = 18532;
            cmd.Parameters["LeaveTypeID1"].Value = cmd.Parameters["LeaveTypeID2"].Value = 0;
            cmd.Parameters["EmployeeCodes1"].Value = cmd.Parameters["EmployeeCodes2"].Value = "6105";
            cmd.Parameters["EmpStatus1"].Value = -1;
            cmd.Parameters["EmpStatus2"].Value = -1;


            OleDbDataAdapter adapter = new OleDbDataAdapter();
            adapter.SelectCommand = cmd;


            bError = false;
            nRowAffected = -1;
            nRowAffected = ADOController.Instance.Fill(adapter, leaveDS, leaveDS.Leave.TableName, _conId, ref bError);
            if (bError)
            {
                ErrorDS.Error err = errDS.Errors.NewError();
                err.ErrorCode = ErrorCode.ERR_DB_OPERATION_FAILED.ToString();
                err.ErrorTier = ErrorTier.ERR_TIER_DL.ToString();
                err.ErrorLevel = ErrorLevel.ERR_LEVEL_SEVER.ToString();
                err.ErrorInfo1 = ActionID.NA_ACTION_GET_LOGIN_USER.ToString();
                errDS.Errors.AddError(err);
                errDS.AcceptChanges();

            }
            leaveDS.AcceptChanges();
            leaveDS.Merge((DataTable)GetLogo());
            leaveDS.AcceptChanges();


            ReportByteData reporteByteData = new ReportByteData();
            var returnString = reporteByteData.ReportData(leaveDS);
            return File(returnString, System.Net.Mime.MediaTypeNames.Application.Octet, "LeaveReport" + ".pdf");
        }

        public DataTable GetLogo()
        {
            string logoPath = @"D:\SYLVIA-RND-ASP-DOT-DOT-CORE\asp-dot-net-core-sylvia\Sylvia\Presentation.Web.AspDotNetCore.Client\wwwroot\img\JTI_Logo.jpg";

            FileStream fs;
            BinaryReader br;
            Byte[] imgbyte;
            fs = new FileStream(logoPath, FileMode.Open, FileAccess.Read);

            br = new BinaryReader(fs);
            imgbyte = br.ReadBytes(Convert.ToInt32((fs.Length)));
            DataTable dt = new DataTable();
            dt.TableName = "Image";
            DataRow drow;
            dt.Columns.Add("img", System.Type.GetType("System.Byte[]"));
            drow = dt.NewRow();
            drow[0] = imgbyte;
            dt.Rows.Add(drow);
            br.Close();
            fs.Close();
            dt.TableName = "Image";
            return dt;
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client
{
    public class LogInModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Web.AspDotNetCore.Client.Pages
{
    public class dashboardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Presentation.Web.AspDotNetCore.Client/Pages/ApplyLeave.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.Pages.ApplyLeaveModel
@using System.Data;

@{
    Layout = "_Dashboard";
}

<h1>Apply Leave</h1>
<p>@ViewData.Eval("loggedInName")</p>


<form>
    <input type="text" asp-for="@Model.Address" />
    <input type="submit" asp-page-handler="GetRdlcReport" value="Submit" />
</form>


<table class="table">

    <thead>
        <tr>
            <th>Employee Name</th>
            <th>Code</th>
            <th>Depatment</th>
            <th>Employee ID</th>
        </tr>

    </thead>
    <tbody>


        @foreach (DataRow item in Model.userDS.Users.Rows)
        {
            <tr>
                <td>@item["EmployeeName"]</td>
                <td>@item["EmployeeCode"]</td>
                <td>@item["DepartmentName"]</td>
                <td>@item["EmployeeID"]</td>
            </tr>
        }

    </tbody>

</table>

<select id="ddlCountry" asp-for="@Model.CountryId" asp-items="@(new SelectList(@Model.countryDS.Countries,"Countryid", "Name"))" class="form-control">
    <option value="" selected>Choose...</option>
</select>

<select id="ddlDivision" asp-for="@Model.DivisionId" asp-items="@(new SelectList(@Model.divisionLs.Division,"Divisionid", "Divisionname"))" class="form-control">
    <option value="" selected>Choose...</option>
</select>



@section Scripts{

    <script type="text/javascript">
        $(function () {
            $('button[data-toggle="ajax-modal"]').click(function (event) {
                alert('button clicked');
            });
            $('#ddlCountry').change(function () {

                var _text = $("#ddlCountry option:selected").text();

                $.ajax({
                    type: "GET",
                    url: "/ApplyLeave?handler=DivisionForAssignLeaveByCountryName",
                    data: { countryName: _text },
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    success: function (data) {
                        items = [];

                        var j = jQuery.parseJSON(data);

                        console.log(j.length);
                        var options;
                        for (var i = 0; i < j.length; i++) {
                            options += '<option value="' + j[i].optionValue + '">' + j[i].optionDisplay + '</option>'
                        }
                        $('#ddlDivision').html(options);




                    },
                    error: function (req, status, error) {
                        console.log(error);
                    }
                    //error: function (e) {
                    //    console.log("ERROR : ", e);
                    //},
                    //failure: function (response) {
                    //    //alert(response);
                    //    console.log(response);
                    //}
                });
            });
        });

    </script>



}

Presentation.Web.AspDotNetCore.Client/Pages/AssignLeave.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.Pages.AssignLeaveModel
@{
    ViewData["Title"] = "AssignLeave";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>AssignLeave</h1>

Presentation.Web.AspDotNetCore.Client/Pages/ChangePassword.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.ChangePasswordModel
@{
    Layout = "_Dashboard";
}
<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Change Password
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse"> </a>
                        <a href="javascript:;" class="reload"> </a>
                        <a href="javascript:;" class="remove"> </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    <form method="post" class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group">
                                <label class="col-md-3 control-label">Current Password</label>
                                <div class="col-md-4">
                                    <input type="password" class="form-control input-circle" placeholder="Current Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">New Password</label>
                                <div class="col-md-4">
                                    <input type="password" class="form-control input-circle" placeholder="New Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Re-type New Password</label>
                                <div class="col-md-4">
                                    <input type="password" class="form-control input-circle" placeholder="Re-type New Password">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn btn-circle green">Change Password</button>
                                    <a  asp-page="/dashboard" class="btn btn-circle grey-salsa btn-outline">Cancel</a>

                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
</div>

Presentation.Web.AspDotNetCore.Client/Pages/Employees.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.Pages.EmployeesModel
@{
}


@{
    Layout = "_Dashboard";
}


<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>
                Employee 
            </h1>
        </div>
        <!-- END PAGE TITLE -->
        <!-- BEGIN PAGE TOOLBAR -->
        <div class="page-toolbar">
            <!-- BEGIN THEME PANEL -->
            @*<div class="btn-group btn-theme-panel">
                    <a href="javascript:;" class="btn dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-settings">
                        </i>
                    </a>
                    <div class="dropdown-menu theme-panel pull-right dropdown-custom hold-on-click">
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <h3>
                                    THEME
                                </h3>
                                <ul class="theme-colors">
                                    <li class="theme-color theme-color-default" data-theme="default">
                                        <span class="theme-color-view">
                                        </span><span class="theme-color-name">Dark Header</span>
                                    </li>
                                    <li class="theme-color theme-color-light active" data-theme="light">
                                        <span class="theme-color-view">
                                        </span><span class="theme-color-name">Light Header</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-8 col-sm-8 col-xs-12 seperator">
                                <h3>
                                    LAYOUT
                                </h3>
                                <ul class="theme-settings">
                                    <li>
                                        Theme Style
                                        <select class="layout-style-option form-control input-small input-sm">
                                            <option value="square">Square corners</option>
                                            <option value="rounded" selected="selected">Rounded corners</option>
                                        </select>
                                    </li>
                                    <li>
                                        Layout
                                        <select class="layout-option form-control input-small input-sm">
                                            <option value="fluid" selected="selected">Fluid</option>
                                            <option value="boxed">Boxed</option>
                                        </select>
                                    </li>
                                    <li>
                                        Header
                                        <select class="page-header-option form-control input-small input-sm">
                                            <option value="fixed" selected="selected">Fixed</option>
                                            <option value="default">Default</option>
                                        </select>
                                    </li>
                                    <li>
                                        Top Dropdowns
                                        <select class="page-header-top-dropdown-style-option form-control input-small input-sm">
                                            <option value="light">Light</option>
                                            <option value="dark" selected="selected">Dark</option>
                                        </select>
                                    </li>
                                    <li>
                                        Sidebar Mode
                                        <select class="sidebar-option form-control input-small input-sm">
                                            <option value="fixed">Fixed</option>
                                            <option value="default" selected="selected">Default</option>
                                        </select>
                                    </li>
                                    <li>
                                        Sidebar Menu
                                        <select class="sidebar-menu-option form-control input-small input-sm">
                                            <option value="accordion" selected="selected">Accordion</option>
                                            <option value="hover">Hover</option>
                                        </select>
                                    </li>
                                    <li>
                                        Sidebar Position
                                        <select class="sidebar-pos-option form-control input-small input-sm">
                                            <option value="left" selected="selected">Left</option>
                                            <option value="right">Right</option>
                                        </select>
                                    </li>
                                    <li>
                                        Footer
                                        <select class="page-footer-option form-control input-small input-sm">
                                            <option value="fixed">Fixed</option>
                                            <option value="default" selected="selected">Default</option>
                                        </select>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>*@
            <!-- END THEME PANEL -->
        </div>
        <!-- END PAGE TOOLBAR -->
    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
    @*<ul class="page-breadcrumb breadcrumb">
            <li><a href="index.html">Home</a> <i class="fa fa-circle"></i></li>
            <li><span class="active">Dashboard</span> </li>
        </ul>*@
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE BASE CONTENT -->
    <!-- BEGIN DASHBOARD STATS 1-->




    <!-- END PAGE BASE CONTENT -->
</div>
<!-- END CONTENT BODY -->

Presentation.Web.AspDotNetCore.Client/Pages/IframeForRDLCReport.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.Pages.IframeForRDLCReportModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Presentation.Web.AspDotNetCore.Client/Pages/LeaveReport.cshtml
@page
@model Presentation.Web.AspDotNetCore.Client.LeaveReportModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "_Dashboard";
}

@foreach (var emp in Model.empDS.Employees)
{
    <div class="card">
        <div class="card-header">
            Show report for : @emp.EmployeeName
        </div>
        <div class="card-body">
            <form asp-page-handler="RdlcReport" method="post">
                <button class="btn btn-success">Show Report</button>
            </form>
            @*<input type="submit" asp-page-handler="RdlcReport" value="Show Report" />*@

        </div>

    </div>
}